"""Add ProdJournalRouteRecords model

Revision ID: 256c4b6c4353
Revises: fd94769cb13e
Create Date: 2026-02-25 13:34:27.627020

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "256c4b6c4353"
down_revision: Union[str, Sequence[str], None] = "fd94769cb13e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ProdJournalRouteRecords",
        sa.Column("Id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("Action", sa.String(length=30), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("JournalId", sa.String(length=80), nullable=True),
        sa.Column("LineNum", sa.Integer(), nullable=False),
        sa.Column("ProdId", sa.String(length=60), nullable=False),
        sa.Column("OprNum", sa.Integer(), nullable=True),
        sa.Column(
            "RecordDate",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column(
            "RecordTime",
            sa.Time(),
            server_default=sa.text("CURRENT_TIME"),
            nullable=False,
        ),
        sa.Column(
            "createdDateTime",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["JournalId"], ["ProdJournal.JournalId"], ondelete="NO ACTION"
        ),
        sa.ForeignKeyConstraint(["ProdId"], ["ProdOrder.ProdId"], ondelete="NO ACTION"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="NO ACTION"),
        sa.PrimaryKeyConstraint("Id"),
        sa.UniqueConstraint(
            "ProdId",
            "JournalId",
            "OprNum",
            "LineNum",
            "Action",
            "user_id",
            "createdDateTime",
            name="uq_prodjournalrouterecord_business",
        ),
    )
    op.create_index(
        op.f("ix_ProdJournalRouteRecords_JournalId"),
        "ProdJournalRouteRecords",
        ["JournalId"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ProdJournalRouteRecords_ProdId"),
        "ProdJournalRouteRecords",
        ["ProdId"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ProdJournalRouteRecords_user_id"),
        "ProdJournalRouteRecords",
        ["user_id"],
        unique=False,
    )
    op.add_column("ProdJournalRoute", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_ProdJournalRoute_user_id"),
        "ProdJournalRoute",
        ["user_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "ProdJournalRoute", "users", ["user_id"], ["id"], ondelete="NO ACTION"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ProdJournalRoute", type_="foreignkey")
    op.drop_index(op.f("ix_ProdJournalRoute_user_id"), table_name="ProdJournalRoute")
    op.drop_column("ProdJournalRoute", "user_id")
    op.drop_index(
        op.f("ix_ProdJournalRouteRecords_user_id"), table_name="ProdJournalRouteRecords"
    )
    op.drop_index(
        op.f("ix_ProdJournalRouteRecords_ProdId"), table_name="ProdJournalRouteRecords"
    )
    op.drop_index(
        op.f("ix_ProdJournalRouteRecords_JournalId"),
        table_name="ProdJournalRouteRecords",
    )
    op.drop_table("ProdJournalRouteRecords")
    # ### end Alembic commands ###
