"""Add production models

Revision ID: 2aaa25d242e5
Revises: 7490ba0f3e2c
Create Date: 2026-02-18 13:48:48.741643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aaa25d242e5'
down_revision: Union[str, Sequence[str], None] = '7490ba0f3e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('InventTable',
    sa.Column('RecId', sa.BigInteger(), nullable=False),
    sa.Column('ItemId', sa.String(length=60), nullable=False),
    sa.Column('ItemName', sa.String(length=250), nullable=True),
    sa.Column('ItemGroupId', sa.String(length=60), nullable=True),
    sa.Column('ItemType', sa.String(length=80), nullable=True),
    sa.Column('PrimaryVendorId', sa.String(length=80), nullable=True),
    sa.Column('NetWeight', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('UnitVolume', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('BOMUnitId', sa.String(length=60), nullable=True),
    sa.Column('MinimumPalletQuantity', sa.Integer(), nullable=True),
    sa.Column('createdDateTime', sa.DateTime(), nullable=True),
    sa.Column('modifiedDateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('RecId')
    )
    op.create_index(op.f('ix_InventTable_ItemId'), 'InventTable', ['ItemId'], unique=True)
    op.create_table('ProdOrder',
    sa.Column('RecId', sa.BigInteger(), nullable=False),
    sa.Column('ProdId', sa.String(length=60), nullable=False),
    sa.Column('ItemId', sa.String(length=60), nullable=True),
    sa.Column('Name', sa.String(length=250), nullable=True),
    sa.Column('ProdGroupId', sa.String(length=60), nullable=True),
    sa.Column('ProdStatus', sa.Integer(), nullable=True),
    sa.Column('ProdPrio', sa.Integer(), nullable=True),
    sa.Column('ProdLocked', sa.Boolean(), nullable=True),
    sa.Column('ProdType', sa.String(length=50), nullable=True),
    sa.Column('SchedStatus', sa.String(length=50), nullable=True),
    sa.Column('SchedDate', sa.Date(), nullable=True),
    sa.Column('SchedStart', sa.DateTime(), nullable=True),
    sa.Column('SchedEnd', sa.DateTime(), nullable=True),
    sa.Column('SchedFromTime', sa.Time(), nullable=True),
    sa.Column('SchedToTime', sa.Time(), nullable=True),
    sa.Column('QtySched', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('QtyStUp', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('FinishedDate', sa.Date(), nullable=True),
    sa.Column('StUpDate', sa.Date(), nullable=True),
    sa.Column('DlvDate', sa.Date(), nullable=True),
    sa.Column('ProdPoolId', sa.String(length=60), nullable=True),
    sa.Column('BOMId', sa.String(length=100), nullable=True),
    sa.Column('RouteId', sa.String(length=100), nullable=True),
    sa.Column('InventLocationId', sa.String(length=60), nullable=True),
    sa.Column('InventBatchId', sa.String(length=60), nullable=True),
    sa.Column('InventSerialId', sa.String(length=60), nullable=True),
    sa.Column('Remark', sa.String(length=250), nullable=True),
    sa.Column('createdDateTime', sa.DateTime(), nullable=True),
    sa.Column('modifiedDateTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('RecId'),
    sa.UniqueConstraint('ProdId', name='uq_prodorder_prodid')
    )
    op.create_index(op.f('ix_ProdOrder_ItemId'), 'ProdOrder', ['ItemId'], unique=False)
    op.create_index(op.f('ix_ProdOrder_ProdId'), 'ProdOrder', ['ProdId'], unique=False)
    op.create_table('ProdBOM',
    sa.Column('RecId', sa.BigInteger(), nullable=False),
    sa.Column('ProdId', sa.String(length=60), nullable=False),
    sa.Column('LineNum', sa.Integer(), nullable=False),
    sa.Column('ItemId', sa.String(length=60), nullable=True),
    sa.Column('BOMQty', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('OprNum', sa.Integer(), nullable=True),
    sa.Column('UnitId', sa.String(length=60), nullable=True),
    sa.Column('InventTransId', sa.String(length=80), nullable=True),
    sa.Column('RawMaterialDate', sa.Date(), nullable=True),
    sa.Column('createdDateTime', sa.DateTime(), nullable=True),
    sa.Column('modifiedDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ProdId'], ['ProdOrder.ProdId'], ),
    sa.PrimaryKeyConstraint('RecId')
    )
    op.create_index(op.f('ix_ProdBOM_ProdId'), 'ProdBOM', ['ProdId'], unique=False)
    op.create_table('ProdJournalRoute',
    sa.Column('RecId', sa.BigInteger(), nullable=False),
    sa.Column('JournalId', sa.String(length=80), nullable=True),
    sa.Column('Voucher', sa.String(length=80), nullable=True),
    sa.Column('LineNum', sa.Integer(), nullable=True),
    sa.Column('TransDate', sa.Date(), nullable=True),
    sa.Column('ProdId', sa.String(length=60), nullable=False),
    sa.Column('OprNum', sa.Integer(), nullable=True),
    sa.Column('JobType', sa.String(length=60), nullable=True),
    sa.Column('WrkCtrId', sa.String(length=80), nullable=True),
    sa.Column('Hours', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('HourPrice', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('QtyGood', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('QtyError', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('EmplId', sa.String(length=80), nullable=True),
    sa.Column('OprFinished', sa.Boolean(), nullable=True),
    sa.Column('JobFinished', sa.Boolean(), nullable=True),
    sa.Column('ExecutedPct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('FromTime', sa.Time(), nullable=True),
    sa.Column('ToTime', sa.Time(), nullable=True),
    sa.Column('OprId', sa.String(length=100), nullable=True),
    sa.Column('Cancelled', sa.Boolean(), nullable=True),
    sa.Column('ErrorCause', sa.String(length=250), nullable=True),
    sa.Column('createdDateTime', sa.DateTime(), nullable=True),
    sa.Column('modifiedDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ProdId'], ['ProdOrder.ProdId'], ),
    sa.PrimaryKeyConstraint('RecId')
    )
    op.create_index(op.f('ix_ProdJournalRoute_ProdId'), 'ProdJournalRoute', ['ProdId'], unique=False)
    op.create_table('ProdRoute',
    sa.Column('RecId', sa.BigInteger(), nullable=False),
    sa.Column('ProdId', sa.String(length=60), nullable=False),
    sa.Column('OprNum', sa.Integer(), nullable=False),
    sa.Column('Level', sa.Integer(), nullable=True),
    sa.Column('OprId', sa.String(length=100), nullable=True),
    sa.Column('WrkCtrId', sa.String(length=80), nullable=True),
    sa.Column('SetupTime', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('ProcessTime', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('ProcessPerQty', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('TranspTime', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('QueueTimeBefore', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('QueueTimeAfter', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('CalcQty', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('OprFinished', sa.Boolean(), nullable=True),
    sa.Column('FromDate', sa.Date(), nullable=True),
    sa.Column('ToDate', sa.Date(), nullable=True),
    sa.Column('FromTime', sa.Time(), nullable=True),
    sa.Column('ToTime', sa.Time(), nullable=True),
    sa.Column('OprPriority', sa.Integer(), nullable=True),
    sa.Column('JobIdProcess', sa.String(length=100), nullable=True),
    sa.Column('createdDateTime', sa.DateTime(), nullable=True),
    sa.Column('modifiedDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ProdId'], ['ProdOrder.ProdId'], ),
    sa.PrimaryKeyConstraint('RecId'),
    sa.UniqueConstraint('ProdId', 'OprNum', name='uq_prodrt_prodid_oprnum')
    )
    op.create_index(op.f('ix_ProdRoute_ProdId'), 'ProdRoute', ['ProdId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ProdRoute_ProdId'), table_name='ProdRoute')
    op.drop_table('ProdRoute')
    op.drop_index(op.f('ix_ProdJournalRoute_ProdId'), table_name='ProdJournalRoute')
    op.drop_table('ProdJournalRoute')
    op.drop_index(op.f('ix_ProdBOM_ProdId'), table_name='ProdBOM')
    op.drop_table('ProdBOM')
    op.drop_index(op.f('ix_ProdOrder_ProdId'), table_name='ProdOrder')
    op.drop_index(op.f('ix_ProdOrder_ItemId'), table_name='ProdOrder')
    op.drop_table('ProdOrder')
    op.drop_index(op.f('ix_InventTable_ItemId'), table_name='InventTable')
    op.drop_table('InventTable')
    # ### end Alembic commands ###
