"""Add department model and make many-to-many between users and roles

Revision ID: 38d86b0fbfac
Revises: 0594996748cc
Create Date: 2025-12-01 00:28:20.398450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d86b0fbfac'
down_revision: Union[str, Sequence[str], None] = '0594996748cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
