"""Fix bug with compose pk in user model

Revision ID: 7490ba0f3e2c
Revises: 38d86b0fbfac
Create Date: 2026-02-12 19:54:53.657676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7490ba0f3e2c'
down_revision: Union[str, Sequence[str], None] = '38d86b0fbfac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
