"""Setup unique constraints

Revision ID: fd94769cb13e
Revises: 2aaa25d242e5
Create Date: 2026-02-19 13:11:13.620886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd94769cb13e'
down_revision: Union[str, Sequence[str], None] = '2aaa25d242e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProdJournal',
    sa.Column('RecId', sa.BigInteger(), nullable=False),
    sa.Column('JournalId', sa.String(length=80), nullable=False),
    sa.Column('Description', sa.String(length=250), nullable=True),
    sa.Column('ProdId', sa.String(length=60), nullable=True),
    sa.Column('OprNum', sa.Integer(), nullable=True),
    sa.Column('JournalType', sa.String(length=50), nullable=True),
    sa.Column('Posted', sa.Boolean(), nullable=True),
    sa.Column('qtyGood', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('qtyError', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('EndJob', sa.Boolean(), nullable=True),
    sa.Column('AutoReportFinished', sa.Boolean(), nullable=True),
    sa.Column('RouteAutoPickList', sa.Boolean(), nullable=True),
    sa.Column('ProdAutoPickList', sa.Boolean(), nullable=True),
    sa.Column('createdDateTime', sa.DateTime(), nullable=True),
    sa.Column('modifiedDateTime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ProdId'], ['ProdOrder.ProdId'], ),
    sa.PrimaryKeyConstraint('RecId'),
    sa.UniqueConstraint('JournalId', name='uq_prodjournal_journalid')
    )
    op.create_index(op.f('ix_ProdJournal_JournalId'), 'ProdJournal', ['JournalId'], unique=False)
    op.create_index(op.f('ix_ProdJournal_ProdId'), 'ProdJournal', ['ProdId'], unique=False)
    op.alter_column('ProdJournalRoute', 'LineNum',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_ProdJournalRoute_JournalId'), 'ProdJournalRoute', ['JournalId'], unique=False)
    op.create_unique_constraint('uq_prodjournalroute_business', 'ProdJournalRoute', ['ProdId', 'JournalId', 'OprNum', 'LineNum'])
    op.create_foreign_key(None, 'ProdJournalRoute', 'ProdJournal', ['JournalId'], ['JournalId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ProdJournalRoute', type_='foreignkey')
    op.drop_constraint('uq_prodjournalroute_business', 'ProdJournalRoute', type_='unique')
    op.drop_index(op.f('ix_ProdJournalRoute_JournalId'), table_name='ProdJournalRoute')
    op.alter_column('ProdJournalRoute', 'LineNum',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_ProdJournal_ProdId'), table_name='ProdJournal')
    op.drop_index(op.f('ix_ProdJournal_JournalId'), table_name='ProdJournal')
    op.drop_table('ProdJournal')
    # ### end Alembic commands ###
