"""Add full_name field for user model

Revision ID: 9dc0b3312bf6
Revises: bd98426d85f8
Create Date: 2025-11-18 15:51:58.053756

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9dc0b3312bf6"
down_revision: Union[str, Sequence[str], None] = "bd98426d85f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("full_name_tsv", postgresql.TSVECTOR(), nullable=True)
    )
    op.create_index(
        "idx_users_full_name_tsv",
        "users",
        ["full_name_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_users_full_name_tsv", table_name="users", postgresql_using="gin")
    op.drop_column("users", "full_name_tsv")
    # ### end Alembic commands ###
