"""Make role_ids in user model accept to be null

Revision ID: bd98426d85f8
Revises: e844693c949d
Create Date: 2025-11-18 02:26:08.344845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd98426d85f8'
down_revision: Union[str, Sequence[str], None] = 'e844693c949d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'devices', ['name'])
    op.alter_column('users', 'role_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_ids',
               existing_type=postgresql.ARRAY(sa.UUID()),
               nullable=False)
    op.drop_constraint(None, 'devices', type_='unique')
    # ### end Alembic commands ###
