"""Add password to user model

Revision ID: e844693c949d
Revises: 28878376c89a
Create Date: 2025-10-21 01:21:36.327650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e844693c949d'
down_revision: Union[str, Sequence[str], None] = '28878376c89a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('finger_token', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'finger_token')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
